seg 11 jul 2022 20:42:14 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/sena b/sena
--- a/sena
+++ b/sena
@@ -29,7 +29,7 @@
 #global
 
 #system
-_VERSION_='2.32.20220711'
+_VERSION_='2.35.20220711'
 DEPENDENCIES=(curl wget grep printf mktemp sort sed awk tail cat tput stat dialog find jq)
 
 #paths/files/urls
@@ -69,14 +69,14 @@ if [ "${COLUMNS}" = "0" ]; then
    COLUMNS=80
 fi
 
-COL=$((${COLUMNS} - 8))
-WCOL=$((${COL} - 2))
+COL=$(( COLUMNS - 8 ))
+#WCOL=$(( COL - 2 ))
 SET_COL="\\033[${COL}G"      # at the $COL char
-SET_WCOL="\\033[${WCOL}G"    # at the $WCOL char
-CURS_UP="\\033[1A\\033[0G"   # Up one line, at the 0'th char
+#SET_WCOL="\\033[${WCOL}G"    # at the $WCOL char
+#CURS_UP="\\033[1A\\033[0G"   # Up one line, at the 0'th char
 CURS_ZERO="\\033[0G"
 
-#[ -e /chili/core.sh ] && source /chili/core.sh
+[ -e /chili/core.sh ] && source /chili/core.sh
 
 sh_playsena()
 {
@@ -247,11 +247,11 @@ sh_checknet()
    log_info_msg "Testing internet from ${xurl}"
  	curl --insecure "$xurl" >/dev/null 2>&1 ||
    {
-	   evaluate_retval
+	   evaluate_retval "$?"
 	   log_msg "No route to server ($xurl) - Rodando com BD sem atualizar."
 	   return 1
    }
-   evaluate_retval
+   evaluate_retval "$?"
    return $?
 }
 
@@ -261,7 +261,7 @@ setvarcolors(){
       tput sgr0; # reset colors
       bold=$(tput bold);
       reset=$(tput sgr0);
-      black=$(tput setaf 0);
+#     black=$(tput setaf 0);
       red=$(tput setaf 1);
       green=$(tput setaf 2);
       yellow=$(tput bold)$(tput setaf 3);
@@ -270,8 +270,8 @@ setvarcolors(){
       cyan=$(tput setaf 6);
       white=$(tput setaf 7);
       orange=$(tput setaf 3);
-      purple=$(tput setaf 125);
-      violet=$(tput setaf 61);
+#     purple=$(tput setaf 125);
+#     violet=$(tput setaf 61);
    else
       bold='';
       reset="\e[0m";
@@ -279,13 +279,13 @@ setvarcolors(){
       cyan="\e[1;36m";
       green="\e[1;32m";
       orange="\e[1;33m";
-      purple="\e[1;35m";
+#     purple="\e[1;35m";
       red="\e[1;31m";
-      violet="\e[1;35m";
+#     violet="\e[1;35m";
       white="\e[1;37m";
       yellow="\e[1;33m";
       pink="\033[35;1m";
-      black="\e[1;30m";
+#     black="\e[1;30m";
    fi
 }
 
@@ -293,14 +293,14 @@ unsetvarcolors()
 {
    bold=
    reset=
-   black=
+#  black=
    blue=
    cyan=
    green=
    orange=
-   purple=
+#   purple=
    red=
-   violet=
+#  violet=
    white=
    yellow=
    pink=
@@ -312,113 +312,104 @@ log_prefix()
    SUCCESS="${green}"           # Success is green
    WARNING="${yellow}"          # Warnings are yellow
    FAILURE="${red}"             # Failures are red
-   INFO="${cyan}"               # Information is light cyan
+#  INFO="${cyan}"               # Information is light cyan
    BRACKET="${blue}"            # Brackets are blue
    BMPREFIX="     "
    DOTPREFIX="  ${blue}::${reset} "
    SUCCESS_PREFIX="${SUCCESS}  *  ${NORMAL}"
    FAILURE_PREFIX="${FAILURE}*****${NORMAL}"
    WARNING_PREFIX="${WARNING}  W  ${NORMAL}"
-   SKIP_PREFIX="${INFO}  S  ${NORMAL}"
+#  SKIP_PREFIX="${INFO}  S  ${NORMAL}"
    SUCCESS_SUFFIX="${BRACKET}[${SUCCESS}  OK  ${BRACKET}]${NORMAL}"
    FAILURE_SUFFIX="${BRACKET}[${FAILURE} FAIL ${BRACKET}]${NORMAL}"
    WARNING_SUFFIX="${BRACKET}[${WARNING} WARN ${BRACKET}]${NORMAL}"
-   SKIP_SUFFIX="${BRACKET}[${INFO} SKIP ${BRACKET}]${NORMAL}"
+#  SKIP_SUFFIX="${BRACKET}[${INFO} SKIP ${BRACKET}]${NORMAL}"
    WAIT_PREFIX="${WARNING}  R  ${NORMAL}"
    WAIT_SUFFIX="${BRACKET}[${WARNING} WAIT ${BRACKET}]${NORMAL}"
    FAILURE_PREFIX="${FAILURE}  X  ${NORMAL}"
 }
 
-evaluate_retval()
+timespec()
 {
-   local error_value="${?}"
-
-   if [ $# -gt 0 ]; then
-      error_value="${1}"
-   fi
-
-   if [ ${error_value} = 0 ]; then
-      log_success_msg2
-   else
-      log_failure_msg2
-   fi
-   return ${error_value}
+#	STAMP="$(echo `date +"%b %d %T %:z"` `hostname`) "
+	STAMP="$(date +"%b %d %T %:z" ) $(hostname)"
+	return 0
 }
 
-log_info_msg2()
+evaluate_retval()
 {
-    echo -n -e "${@}"
-    logmessage=`echo "${@}" | sed 's/\\\033[^a-zA-Z]*.//g'`
-    echo -n -e "${logmessage}" >> ${BOOTLOG}
-    return 0
+   local error_value="$?"
+
+   if [ $# -gt 0 ]; then
+      error_value="$1"
+   fi
+
+   if [ "${error_value}" = 0 ]; then
+      log_success_msg2 ""
+   else
+      log_failure_msg2 ""
+   fi
+   return "${error_value}"
 }
 
 log_failure_msg2()
 {
-   printf "${BMPREFIX}${@}"
-   printf "${CURS_ZERO}${FAILURE_PREFIX}${SET_COL}${FAILURE_SUFFIX}\n"
+   echo -n -e "${BMPREFIX}${*}"
+   echo -e "${CURS_ZERO}${FAILURE_PREFIX}${SET_COL}${FAILURE_SUFFIX}"
    return 0
-}
-
-timespec()
-{
-	STAMP="$(echo `date +"%b %d %T %:z"` `hostname`) "
-	return 0
 }
 
 log_success_msg()
 {
-    echo -n -e "${BMPREFIX}${@}"
-    echo -e "${CURS_ZERO}${SUCCESS_PREFIX}${SET_COL}${SUCCESS_SUFFIX}"
-    logmessage=`echo "${@}" | sed 's/\\\033[^a-zA-Z]*.//g'`
-    timespec
-    echo -e "${STAMP} ${logmessage} OK" >> ${BOOTLOG}
-    return 0
+	info "{*}"
+	echo -n -e "${BMPREFIX}${*}"
+	echo -e "${CURS_ZERO}${SUCCESS_PREFIX}${SET_COL}${SUCCESS_SUFFIX}"
+	return 0
 }
 
 log_success_msg2()
 {
-   printf "${BMPREFIX}${@}"
-   printf "${CURS_ZERO}${SUCCESS_PREFIX}${SET_COL}${SUCCESS_SUFFIX}\n"
+   echo -n -e "${BMPREFIX}${*}"
+   echo -n -e "${CURS_ZERO}${SUCCESS_PREFIX}${SET_COL}${SUCCESS_SUFFIX}\n"
    return 0
 }
 
 log_warning_msg()
 {
-   printf "${BMPREFIX}${@}"
-   printf "${CURS_ZERO}${WARNING_PREFIX}${SET_COL}${WARNING_SUFFIX}\n"
+   echo -n -e "${BMPREFIX}${*}"
+   echo -n -e "${CURS_ZERO}${WARNING_PREFIX}${SET_COL}${WARNING_SUFFIX}"
    return 0
 }
 
 
 log_wait_msg()
 {
-   printf "${BMPREFIX}${@}"
-   printf "${CURS_ZERO}${WAIT_PREFIX}${SET_COL}${WAIT_SUFFIX}\n"
+   echo -n -e "${BMPREFIX}${*}"
+   echo -e "${CURS_ZERO}${WAIT_PREFIX}${SET_COL}${WAIT_SUFFIX}"
    return 0
 }
 
 log_info_msg()
 {
-   echo -n -e "${BMPREFIX}${@}"
+   echo -n -e "${BMPREFIX}${*}"
    return 0
 }
 
 log_msg()
 {
-   printf "${DOTPREFIX}${@}\n"
-   return 0
+	echo -n -e "${DOTPREFIX}${*}"
+	return 0
 }
 
 toupper()
 {
-	declare -u TOUPPER=${@}
+	declare -u TOUPPER="${*}"
 	echo -e "${TOUPPER}"
 }
 
 tolower()
 {
-	declare -l TOLOWER=${@}
+	declare -l TOLOWER="${*}"
 	echo -e "${TOLOWER}"
 }
 
@@ -523,33 +514,33 @@ sh_compareGREP()
 sh_atualizaBD()
 {
 	contLinha=$1
-   #wget $SITE$contLinha --no-check-certificate -qO- > $fileUltSorteioAtualizado 						# mais lento
-   curl --compressed --insecure -s --url "$SITE$contLinha" --output $fileUltSorteioAtualizado		# mais rápido
+   #wget $SITE$contLinha --no-check-certificate -qO- > "$fileUltSorteioAtualizado" 						# mais lento
+   curl --compressed --insecure -s --url "$SITE$contLinha" --output "$fileUltSorteioAtualizado"		# mais rápido
 
 	if [[ -z $(command -v jq) ]]; then
-		listaDezenas=$(sed -n '/listaDezenas/,/],/p' $fileUltSorteioAtualizado | sed 's/[^0-9]//g' | sed -e "s/\r//g" | awk -F"-" '{print $1}')
-	   listaDezenas=$(echo $listaDezenas | cut -c1-18)
-	   dataApuracao=$(grep '"dataApuracao":' $fileUltSorteioAtualizado | awk '{print $2}' | sed 's/\"//g' | sed 's/\,//g' | sed -e "s/\r//g" )
-	   valorEstimadoProximoConcurso=$(grep '"valorEstimadoProximoConcurso":' $fileUltSorteioAtualizado | awk -F"-" '{print $2}' | sed 's/\,//g')
-	   dadosSena=$(sed -n '/"faixa": 1/,/},/p' $fileUltSorteioAtualizado)
-	   dadosQuina=$(sed -n '/"faixa": 2/,/},/p' $fileUltSorteioAtualizado)
-	   dadosQuadra=$(sed -n '/"faixa": 3/,/},/p' $fileUltSorteioAtualizado)
-	   numGanhadoresSena=$(echo $dadosSena | awk -F'"' '{ print $5 }' | sed 's/://g' | sed 's/,//g')
-	   valorPremioSena=$(echo $dadosSena | awk -F'"' '{print $7}' | sed 's/://g' | sed 's/,//g')
+		listaDezenas=$(sed -n '/listaDezenas/,/],/p' "$fileUltSorteioAtualizado" | sed 's/[^0-9]//g' | sed -e "s/\r//g" | awk -F"-" '{print $1}')
+	   listaDezenas=$(echo "$listaDezenas" | cut -c1-18)
+	   dataApuracao=$(grep '"dataApuracao":' "$fileUltSorteioAtualizado" | awk '{print $2}' | sed 's/\"//g' | sed 's/\,//g' | sed -e "s/\r//g" )
+#	   valorEstimadoProximoConcurso=$(grep '"valorEstimadoProximoConcurso":' "$fileUltSorteioAtualizado" | awk -F"-" '{print $2}' | sed 's/\,//g')
+	   dadosSena=$(sed -n '/"faixa": 1/,/},/p' "$fileUltSorteioAtualizado")
+#	   dadosQuina=$(sed -n '/"faixa": 2/,/},/p' "$fileUltSorteioAtualizado")
+#	   dadosQuadra=$(sed -n '/"faixa": 3/,/},/p' "$fileUltSorteioAtualizado")
+	   numGanhadoresSena=$(echo "$dadosSena" | awk -F'"' '{ print $5 }' | sed 's/://g' | sed 's/,//g')
+	   valorPremioSena=$(echo "$dadosSena" | awk -F'"' '{print $7}' | sed 's/://g' | sed 's/,//g')
 	   valorPremioSena=$(awk '{printf "%.2f\n" ,$1}' <<< "$valorPremioSena")
-	   valorPremioSenaFormat=$(echo $valorPremioSena  | sed -e :a -e 's/\(.*[0-9]\)\([0-9]\{3\}\)/\1,\2/;ta' | tr ',.' '.,')
+	   valorPremioSenaFormat=$(echo "$valorPremioSena" | sed -e :a -e 's/\(.*[0-9]\)\([0-9]\{3\}\)/\1,\2/;ta' | tr ',.' '.,')
 	   varLinhaInteira=$(echo $contLinha - $dataApuracao - $listaDezenas - $valorPremioSenaFormat - $numGanhadoresSena)
 	   echo $varLinhaInteira |& tee -a $fileresult
 	else # usando jq
-		listaDezenas=$(jq -r '.listaDezenas[range(0;6)]' $fileUltSorteioAtualizado)
-	   dataApuracao=$(jq -r '.dataApuracao' $fileUltSorteioAtualizado)
-	   valorEstimadoProximoConcurso=$(jq -r '.valorEstimadoProximoConcurso' $fileUltSorteioAtualizado)
-	   numGanhadoresSena=$(jq -r '.listaRateioPremio[0].numeroDeGanhadores' $fileUltSorteioAtualizado)
-	   valorPremioSena=$(jq -r '.listaRateioPremio[0].valorPremio' $fileUltSorteioAtualizado|awk '{printf "%.2f\n" ,$1}'|sed -e :a -e 's/\(.*[0-9]\)\([0-9]\{3\}\)/\1,\2/;ta' | tr ',.' '.,')
-	   numGanhadoresQuina=$(jq -r '.listaRateioPremio[1].numeroDeGanhadores' $fileUltSorteioAtualizado)
-	   valorPremioQuina=$(jq -r '.listaRateioPremio[1].valorPremio' $fileUltSorteioAtualizado|awk '{printf "%.2f\n" ,$1}'|sed -e :a -e 's/\(.*[0-9]\)\([0-9]\{3\}\)/\1,\2/;ta' | tr ',.' '.,')
-	   numGanhadoresQuadra=$(jq -r '.listaRateioPremio[2].numeroDeGanhadores' $fileUltSorteioAtualizado)
-	   valorPremioQuadra=$(jq -r '.listaRateioPremio[2].valorPremio' $fileUltSorteioAtualizado|awk '{printf "%.2f\n" ,$1}'|sed -e :a -e 's/\(.*[0-9]\)\([0-9]\{3\}\)/\1,\2/;ta' | tr ',.' '.,')
+		listaDezenas=$(jq -r '.listaDezenas[range(0;6)]' "$fileUltSorteioAtualizado")
+	   dataApuracao=$(jq -r '.dataApuracao' "$fileUltSorteioAtualizado")
+#	   valorEstimadoProximoConcurso=$(jq -r '.valorEstimadoProximoConcurso' "$fileUltSorteioAtualizado")
+	   numGanhadoresSena=$(jq -r '.listaRateioPremio[0].numeroDeGanhadores' "$fileUltSorteioAtualizado")
+	   valorPremioSena=$(jq -r '.listaRateioPremio[0].valorPremio' "$fileUltSorteioAtualizado"|awk '{printf "%.2f\n" ,$1}'|sed -e :a -e 's/\(.*[0-9]\)\([0-9]\{3\}\)/\1,\2/;ta' | tr ',.' '.,')
+	   numGanhadoresQuina=$(jq -r '.listaRateioPremio[1].numeroDeGanhadores' "$fileUltSorteioAtualizado")
+	   valorPremioQuina=$(jq -r '.listaRateioPremio[1].valorPremio' "$fileUltSorteioAtualizado"|awk '{printf "%.2f\n" ,$1}'|sed -e :a -e 's/\(.*[0-9]\)\([0-9]\{3\}\)/\1,\2/;ta' | tr ',.' '.,')
+	   numGanhadoresQuadra=$(jq -r '.listaRateioPremio[2].numeroDeGanhadores' "$fileUltSorteioAtualizado")
+	   valorPremioQuadra=$(jq -r '.listaRateioPremio[2].valorPremio' "$fileUltSorteioAtualizado"|awk '{printf "%.2f\n" ,$1}'|sed -e :a -e 's/\(.*[0-9]\)\([0-9]\{3\}\)/\1,\2/;ta' | tr ',.' '.,')
 	   varLinhaInteira=$(echo $contLinha - $dataApuracao - $listaDezenas - $valorPremioSena - $numGanhadoresSena - $valorPremioQuina - $numGanhadoresQuina - $valorPremioQuadra - $numGanhadoresQuadra)
 	   tee -a $fileresult <<< "$varLinhaInteira"
 	fi
@@ -562,31 +553,31 @@ sh_checkresultadosfaltantes()
 	local -i n=0
 	local value
 	local array
-	local filetmp=$(mktemp)
+	local filetmp
 
-
-	log_info_msg "Checando a integridade do BD. Aguarde..."; evaluate_retval
-	if !(( force )); then
+	log_info_msg "Checando a integridade do BD. Aguarde..."; evaluate_retval "$?"
+	if ! (( force )); then
 		if [[ $numUltSorteioGravado -eq 0 ]]; then
 			if sh_checknet "${URL_GITHUB_RESULTADOSENA}"; then
 				#curl --compressed --insecure -s --url "${URL_GITHUB_RESULTADOSENA}" --output $fileresult
 				log_info_msg "Baixando arquivo ${URL_GITHUB_RESULTADOSENA}"
-				if ! wget -c --no-check-certificate "${URL_GITHUB_RESULTADOSENA}" -qO - > $fileresult; then
-					echo "#" >> $fileresult
+				if ! wget -c --no-check-certificate "${URL_GITHUB_RESULTADOSENA}" -qO - > "$fileresult"; then
+					echo "#" >> "$fileresult"
 				fi
-				evaluate_retval
+				evaluate_retval "$?"
 			else
-				evaluate_retval
-				echo "#" >> $fileresult
+				evaluate_retval "$?"
+				echo "#" >> "$fileresult"
 			fi
 		fi
 	else
-		echo "#" > $fileresult
+		echo "#" > "$fileresult"
 	fi
 
-	seq "$numUltSorteio" > $filetmp
-	local array=$(awk 'NR == FNR {file1[$1]++; next} !($0 in file1)' $fileresult $filetmp)
-	rm -f $filetmp 2> /dev/null
+	filetmp=$(mktemp)
+	seq "$numUltSorteio" > "$filetmp"
+	array=$(awk 'NR == FNR {file1[$1]++; next} !($0 in file1)' "$fileresult" "$filetmp")
+	rm -f "$filetmp" 2> /dev/null
 
 	for value in $array
 	do
@@ -615,7 +606,7 @@ sh_update()
 	log_info_msg "Coletando dados dos ultimo resultado da ${cyan}MegaSena${reset} publicado pela ${blue}CAIXA${reset}"
 #	wget "$SITE" --no-check-certificate -qO- > "$fileUltSorteio"					# mais lento
    curl --compressed --insecure -s --url "$SITE" --output "$fileUltSorteio"	# mais rápido
-   evaluate_retval
+   evaluate_retval "$?"
 
 	#### COLETANDO O NUMERO DO ULTIMO SORTEIO NA CAIXA e GRAVADO NO BD
 	if [[ -z $(command -v jq) ]]; then
@@ -632,18 +623,18 @@ sh_update()
 
 	#### COLETANDO DADOS DOS DOS RESULTADOS NAO INCLUÍDOS NO BD
 	declare -i falta=$(( numUltSorteio - numUltSorteioGravado ))
-	log_info_msg "Sorteios feitos pela CAIXA : ${red}$numUltSorteio${reset}"; evaluate_retval
-	log_info_msg "Sorteios registrados no BD : ${yellow}$numUltSorteioGravado${reset}"; evaluate_retval
-	log_info_msg "${cyan}${falta}${reset} novo(s) registro(s) encontrado(s)!"; evaluate_retval
+	log_info_msg "Sorteios feitos pela CAIXA : ${red}$numUltSorteio${reset}"; evaluate_retval "$?"
+	log_info_msg "Sorteios registrados no BD : ${yellow}$numUltSorteioGravado${reset}"; evaluate_retval "$?"
+	log_info_msg "${cyan}${falta}${reset} novo(s) registro(s) encontrado(s)!"; evaluate_retval "$?"
 	sh_checkresultadosfaltantes "$numUltSorteioGravado" "$numUltSorteio"
 	sort -g -u "$fileresult" > "$fileresult.sort"
 	cp "$fileresult.sort" "$fileresult"
 	rm -f "$fileresult.sort" 2> /dev/null
-	log_info_msg "${green}OK. Banco de Dados atualizado!"; evaluate_retval
+	log_info_msg "${green}OK. Banco de Dados atualizado!"; evaluate_retval "$?"
 
 	#### REMOVENDO ARQUIVOS TEMPORARIOS
-	rm $fileUltSorteio 2> /dev/null
-	rm $fileUltSorteioAtualizado 2> /dev/null
+	rm "$fileUltSorteio" 2> /dev/null
+	rm "$fileUltSorteioAtualizado" 2> /dev/null
 }
 
 sh_version()
@@ -794,7 +785,6 @@ setvarcolors
 log_prefix
 check_deps
 sh_ascii-lines
-param="$@"
 
 [[ -z $1 ]] && { sh_usage; exit $(( $# ? 0 : 1 ));}
 init "$@"
